### PR TITLE
don't run as gearman worker

### PR DESCRIPTION
**Pull request by azylman**

### CODE REVIEW

**Comment by azylman** [comment]
tested this and it's working

**Comment by schimmy** [comment]
aww, I kind of liked that it was going through gearman for consistency, even though it doesn't make too much sense for utility :-/ That's fine though

**Comment by schimmy** [comment]
Is the worker load computed elsewhere? otherwise we need to keep that info here...
overall I'd appreciate more context on your PRs - I never know what's going on / the reasons for the PR :(

**Comment by azylman** [comment]
@schimmy Sorry, I thought it was fine because we'd talked through this in person. We shouldn't need to calculate load in our metrics, it should be calculated by alerting infrastructure - we can have librato calculate + alert on load.

**Comment by schimmy** [comment]
oh right, now I remember. :-P
By the way, I am 100% terrible at remembering things just said to me but not written down, FYI!!

**Pull request merged**
