### PR TITLE
Update launch yml to be gearmand discovery compatible

### PR DESCRIPTION
**Pull request by xavi-**
You were assigned this PR as the most active committer to this repo. This PR was autogenerated.

**Before your merge!**:
- Please upgrade your gearman to v0.4.0 in your Dockerfile.  @xavi- thought it was too scary to this automatically.
- Please make sure the corresponding salt changes are merged to master: https://github.com/Clever/salt/pull/1262

For context, see https://clever.atlassian.net/browse/INFRA-1179.

### CODE REVIEW

**Comment by azylman** [comment]
This repo doesn't use gearcmd

**Comment by xavi-** [comment]
I see, it looks like it connects directly to gearman.  So for this change to work, gearman-load-logger will need to be migrated to use discovery-go, which seems simple enough.

I can go a head and do the migration if you all are on board.  Otherwise this PR can just be closed.

**Comment by schimmy** [comment]
sounds good @xavi-! I'm happy for it to be migrated :)

**Comment by xavi-** [comment]
Okie dokie.  Closing PR for now.

**Pull request closed without merging**
